CREATE TABLE "USR_STORE_MAIN"."TBL_MEDICIN_TYPE"
  (
    "MED_TYP_ID"    NUMBER,
    "MED_TYP_CODE"  VARCHAR2(5 BYTE),
    "MED_TYPE_NAME" VARCHAR2(50 BYTE),
    "ACTIVE"        CHAR(1 BYTE),
    "MESURE"        VARCHAR2(5 BYTE),
    PRIMARY KEY ("MED_TYP_ID")
  );
