CREATE TABLE "USR_STORE_MAIN"."TBL_COMPANY_NAME"
  (
    "COMP_ID"   NUMBER,
    "COMP_CODE" VARCHAR2(5 BYTE),
    "COMP_NAME" VARCHAR2(50 BYTE),
    "ACTIVE"    CHAR(1 BYTE),
    PRIMARY KEY ("COMP_ID")
  );
